package edu.pdx.cs410J.kamakshi;

import edu.pdx.cs410J.AbstractPhoneBill;
import edu.pdx.cs410J.ParserException;
import edu.pdx.cs410J.PhoneBillParser;

import java.io.*;

/**
 * This class parses the text output generated by a
 * <code>TextDumper</code> and creates a Phone Bill.
 * It also Implements PhoneBillParser and its method Parse().
 *
 * @see TextDumper
 * @author Kamakshi Nagar
 */
public class TextParser implements PhoneBillParser {

    private PhoneBill phoneBill; //The Phone Bill which we are creating.
    private BufferedReader in; //The Phone Bill will be Read from here.

    private static void debug(String s) {
         System.out.println(s);
    }
    /**
     * Creates a new text parser that reads its input from a file of a
     * given name.
     */
    public TextParser(String fileName) throws FileNotFoundException {
        this(new File(fileName));
    }
    /**
     * Creates a new text parser that reads its input from the given
     * file.
     */
    public TextParser(File file) throws FileNotFoundException {
        this(new FileReader(file));
    }
    /**
     * Creates a new text parser that reads its input from the given
     * writer.  This lets us read from a sources other than files.
     */
    public TextParser(Reader reader) {
        this.in = new BufferedReader(reader);
    }

    /**
     * Parses the specified input source (like file) and from it creates a Phone Bill.
     *
     * @return  PhoneBill that contains the Phone Calls
     * @throws ParserException
     *         The data/text source is malformatted
     */
    @Override
    public AbstractPhoneBill parse() throws ParserException {

        this.phoneBill = new PhoneBill();
        try{
        while(this.in.ready()){
            String line = this.in.readLine();
            debug(" " + line);
        }
        }catch(IOException ex){
            System.err.println("There is an error: "+ ex);
        }
        return this.phoneBill;
    }
}
